project_id = "zvvvfitrolqeyrfszfcv"

[functions.auth-guard]
verify_jwt = false

[functions.approve-teacher]
verify_jwt = false

[functions.teacher-onboarding]
verify_jwt = false

[functions.teacher-profile]
verify_jwt = false

[functions.teacher-documents]
verify_jwt = false

[functions.public-profile]
verify_jwt = false

[functions.agenda]
verify_jwt = false

[functions.booking]
verify_jwt = false
